### ISSUE TITLE
The dropdown doesn't move up to avoid keyboard hiding it

### ISSUE THREAD

**Issue by ronytesler** [salim-lachdhaf/searchable_dropdown#150]
Before clicking the search box:
![image](https://user-images.githubusercontent.com/9344207/114956305-45838780-9e67-11eb-863d-29ec4085cf62.png)
After:
![image](https://user-images.githubusercontent.com/9344207/114956337-546a3a00-9e67-11eb-81c0-cd7c41394085.png)

The screen is not scrollable when the DropdownSearch is open.

**Comment by Abhijit-Revamp** [comment]
Such a beautiful component hidden by keyboard. Please help

**Comment by vasilich6107** [comment]
@ronytesler @Abhijit-Revamp you case seems to be fixable by using another type of dropdown mode.
As you se - you are on mobile and screen is not so big like on desktop. But you are trying to use the same approach as you do on desktop. This is the main issue in this case. Cause technically menu mode is supposed to be used when there are a little amount of options whout search. 
It will be better for you to use one of two other modes to open the full screen popup which will give you more place for keyboard and options.

**Comment by salim-lachdhaf** [comment]
@vasilich6107 great and exact answer, menu mode meant to behave like this. we will see in the future for some possible changes but for now we keep that as it is

**Comment by Isuru-Nanayakkara** [comment]
Ran into this on a tablet as well. Unlike on a phone, it has a lot of space. But unfortunately can't utilise that due to the text field being near the bottom of the screen.

It would be nice to have the keyboard avoidance support for this mode as well. Maybe showing the dropdown upwards if the keyboard is presented there is not enough space downward. Just a suggestion.
