### ISSUE TITLE
DropdownSearch.multiSelection does no allow to specify generic type

### ISSUE THREAD

**Issue by vasilich6107** [salim-lachdhaf/searchable_dropdown#207]
`DropdownSearch.multiSelection` has no ability to pass down the type of items

**Comment by salim-lachdhaf** [comment]
yes , and no,
in fact the type will automatically detected from the type passed in the params, like selectedItems ....

**Comment by vasilich6107** [comment]
![image](https://user-images.githubusercontent.com/6721286/125160791-87327e80-e187-11eb-89e8-964d8790ab1b.png)

**Comment by vasilich6107** [comment]
Simple check - I added list of ints instead list of strings...

**Comment by vasilich6107** [comment]
![image](https://user-images.githubusercontent.com/6721286/125160809-a7623d80-e187-11eb-91a6-953bf6742dc4.png)

**Comment by salim-lachdhaf** [comment]
i will fix it, thnx

**Comment by salim-lachdhaf** [comment]
@vasilich6107  after checking you can pass your type simply like this `DropdownSearch<int>.multiSelection`

**Comment by vasilich6107** [comment]
There is another issue.
I'm passing an `int` but the list of items could be `int?`

![image](https://user-images.githubusercontent.com/6721286/125207052-e7621700-e292-11eb-9073-e974ca475829.png)

**Comment by vasilich6107** [comment]
It is also allows selectedItems to be `null` 
![image](https://user-images.githubusercontent.com/6721286/125207086-0365b880-e293-11eb-9be2-41219a7b667c.png)

**Comment by vasilich6107** [comment]
And type of `v` in `validatorMultiSelection` is `List<int?>?`
But it seems logical to be `List<int>`

Cause in single selection mode `null` describes `nothing selected`
In multi selection mode `[]` is enough to describe `nothing selected`

**Comment by salim-lachdhaf** [comment]
it's logical to make it List<T?> because:
single mode: not impacted
multiSeletion : user can enter or have a list of nullable object like example.

in particular, in single mode ,if user select a null value we will have List<null>. => yes THE USER selected NULL.
note all functions like onChange return null normally, even programmatically the `getSelectedItem `returns null. 
```
T? get getSelectedItem =>
      getSelectedItems.isEmpty ? null : getSelectedItems.first;
```
`List<null> == [] == null` in single mode.
the difference :
`List<null>` => user selected null empty
`[]`  (passed null [clear] by user) => user clear the selected item

This is logic for me.

**Comment by salim-lachdhaf** [comment]
edit:
Yes there is bug, if you pass `<int>` your list should not accept null => to accept null the user pass `<int?>`
