### ISSUE TITLE
Duplicate GlobalKey detected in widget tree

### ISSUE THREAD

**Issue by komritza** [salim-lachdhaf/searchable_dropdown#353]
I am getting this error:
``` 
The following assertion was thrown while finalizing the widget tree:
Duplicate GlobalKey detected in widget tree.


The following GlobalKey was specified multiple times in the widget tree. This will lead to parts of the widget tree being truncated unexpectedly, because the second time a key is seen, the previous instance is moved to the new location. The key was:
- [LabeledGlobalKey<SelectionWidgetState<String>>#b2412]
This was determined by noticing that after the widget with the above global key was moved out of its previous parent, that previous parent never updated during this frame, meaning that it either did not update at all or updated before the widget was moved, in either case implying that it still thinks that it should have a child with that global key.
The specific parent that did not update after having one or more children forcibly removed due to GlobalKey reparenting is:
- ConstrainedBox(BoxConstraints(w=332.0, 0.0<=h<=Infinity), renderObject: RenderConstrainedBox#c2714 relayoutBoundary=up27)
A GlobalKey can only be specified on one widget at a time in the widget tree.
When the exception was thrown, this was the stack
#0      BuildOwner.finalizeTree.<anonymous closure>
package:flutter/…/widgets/framework.dart:2939
#1      BuildOwner.finalizeTree
package:flutter/…/widgets/framework.dart:2964
#2      WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:884
#3      RendererBinding._handlePersistentFrameCallback
package:flutter/…/rendering/binding.dart:319
#4      SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1143
#5      SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1080
#6      SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:996
#10     _invoke (dart:ui/hooks.dart:166:10)
#11     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#12     _drawFrame (dart:ui/hooks.dart:129:31)
(elided 3 frames from dart:async)

```

Steps to reproduce(you can reproduce it with example code):
1) Click on `Menu mode` or `Menu mode with helper` so that dropdown is open
2) Double tap fast on the field above `Menu` 

Any tips of how to solve this? 
Btw. great package, really nice to use it.

**Comment by salim-lachdhaf** [comment]
the plugin it's not uses `GlobalKey` , only on the example page.

**Comment by MalikSamiAwan** [comment]
same error

**Comment by s2yed** [comment]
======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
Duplicate GlobalKey detected in widget tree.

The following GlobalKey was specified multiple times in the widget tree. This will lead to parts of the widget tree being truncated unexpectedly, because the second time a key is seen, the previous instance is moved to the new location. The key was:
- [LabeledGlobalKey<SelectionWidgetState<AccountTreeModelDropDown>>#23b22]
This was determined by noticing that after the widget with the above global key was moved out of its previous parent, that previous parent never updated during this frame, meaning that it either did not update at all or updated before the widget was moved, in either case implying that it still thinks that it should have a child with that global key.

**Comment by salim-lachdhaf** [comment]
check this https://stackoverflow.com/questions/49371221/duplicate-globalkey-detected-in-widget-tree.
it's a hot reload issue.
