### ISSUE TITLE
Documentation is not up to date

### ISSUE THREAD

**Issue by Wissperwind** [salim-lachdhaf/searchable_dropdown#373]
Hi,
Please update the examples on the start page:
`import 'package:dropdown_search/dropdownSearch.dart';`
The import is not correct and the examples use deprecated parameters like:
```
label: "Menu mode",
hint: "country in menu mode",
```

**Comment by vasilich6107** [comment]
@Wissperwind don't forget that it's open source.
Do not hesitate to make PR with your suggestions.

**Comment by salim-lachdhaf** [comment]
you are mixing between documentation and examples.
what you see in readme is simple examples.

document is always uptodate , it's automatically generated by pub.dev.

**Comment by btraas** [comment]
Either way, the readme is not up to date. 

Label and hint are suggested and deprecated. 
- "showSelectedItem" as shown in the example does not exist since version 1.0.
- Sample code does not produce the result in the screenshots because "showSearchBox" is now `false` by default.

Examples README also has incorrect info.
https://github.com/salim-lachdhaf/searchable_dropdown/tree/master/example

For example: "autoFocusSearchBox: the search box will be focused if true" <- this property does not exist, and there's no obvious alternative unless we look into the changelog.

I'd suggest adding a disclaimer to the root README and examples README that they are not up to date.
