### ISSUE TITLE
Restore dropdownButtonBuilder or add showDropdownButton property

### ISSUE THREAD

**Issue by slavap** [salim-lachdhaf/searchable_dropdown#390]
Previously it was possible to remove dropdown button easily like that:
```dart
dropdownButtonBuilder: readOnly ? (context) => SizedBox.shrink() : null,
```
In version 3.0.1 dropdownButtonBuilder was removed, so now dropdownButton could not be hidden if necessary.
So return back dropdownButtonBuilder (preferable) or at least add showDropdownButton property.

As workaround I'm using the following code now:
```dart
dropdownButtonProps: readOnly
        ? IconButtonProps(icon: SizedBox.shrink(), constraints: BoxConstraints(maxWidth: 0, maxHeight: 0))
        : null,
```

**Comment by salim-lachdhaf** [comment]
hi @slavap , did you think to use enbled to false ? istead of remove the icon .... ?

**Comment by slavap** [comment]
@salim-lachdhaf In my case enabled is not enough, requirements are that drop down button should be hidden in case of read only UI. In some cases it is convenient to be able to fully customise drop down button as well, that’s why I’m asking to restore dropdownButtonBuilder

**Comment by salim-lachdhaf** [comment]
i see your need. but we can't go back , first in your case both cases you have to do a workaround to hide icon ...
the main reason why we can't go back is that before we do not give the possiblité to user to change all proporties related to click; like highlightColor, splashRadius, splashColor .... (because the `click `is obsorbed by our widget ...)

for this we remove the `dropdownButtonBuilder` and give all possible properties to be customized by the user.

**Comment by slavap** [comment]
@salim-lachdhaf Not going back is ok, what about adding showDropdownButton property? You already has similar for clear button.
