### ISSUE TITLE
InputDecorator isEmpty should not depend from assigned dropdownBuilder

### ISSUE THREAD

**Issue by slavap** [salim-lachdhaf/searchable_dropdown#4]
Currently if dropdownBuilder is assigned, it's not possible to make label text shown as placeholder.
To fix this problem minor change is needed:
```dart
return InputDecorator(
                  isEmpty: value == null && widget.dropdownBuilder == null,
```
Check && widget.dropdownBuilder == null should be deleted, otherwise no way to get label shown as placeholder.

**Comment by salim-lachdhaf** [comment]
Thank you for your feedback.
Sadly this is not a bug, however, if we do like you said and we remove the test, in this case if the user handle the item==null, the label will be no more visible on the top of the field (it will be hidden by user custom dropdown). Here us an example:
```Widget _customDropDownExample(
      BuildContext context, UserModel item, String itemDesignation) {
    return Container(
      child: (item?.avatar == null)
          ? ListTile(
              contentPadding: EdgeInsets.all(0),
              leading: CircleAvatar(),
              title: Text("No item selected"),
            )
          : ListTile(
              contentPadding: EdgeInsets.all(0),
              leading: CircleAvatar(
                backgroundImage: NetworkImage(item.avatar),
              ),
              title: Text(item.name),
              subtitle: Text(item.createdAt.toString()),
            ),
    );
  }```

This case is already illustrated in the plugin examlpe.

**Comment by slavap** [comment]
@salim-lachdhaf I'm not saying removing check is the only solution, BUT it should be possible to have standard placeholder working (small text on top when not null, large placeholder text if null) in case dropdownBuilder defined. It could be additional property, like bool dropdownBuilderSupportsNull

**Comment by salim-lachdhaf** [comment]
thank you for the suggesion But to prevent more complexity, it will be better to let user handle it it he choose to customize the dropdownBuilder, other wises a lot of questions will be asked , where we gonna put this small holder , witch color , size .... witch could cause UI problems with the custom dropdownBuilder. For this as solution it will be better to consider the inputDecorator as non empty and get the material design as result.

**Comment by slavap** [comment]
@salim-lachdhaf Not sure I'm following your idea, probably we just don't understand each other.
I'm talking about this problem (when dropdownBuilder is assigned):
![image](https://user-images.githubusercontent.com/4129763/81766801-b4a07100-948b-11ea-82af-2f520d307831.png)
It is not possible to solve it any meaningful way.
If dropdownBuilder is not assigned I have normal material behavior:
![image](https://user-images.githubusercontent.com/4129763/81766954-1c56bc00-948c-11ea-80f1-547194049e76.png)
![image](https://user-images.githubusercontent.com/4129763/81767002-36909a00-948c-11ea-9c2e-bb058e722d21.png)

**Comment by salim-lachdhaf** [comment]
i understand exactly what you want to say, but maybe you didn't understand my point, However, you are giving a specific case where the user use a custom dropdownBuilder but he works only with `item != null` and just put an empty container if `item == null`. But this maybe should be a user problem ! because he decide to custimize the dropdownBuilder instead of manage both cases of the item. why i saying that , because we could not detect if the user filled the both cases or not, and if we do as you said (remove `&& dropdownBuilder ==null`) we could lose the material behavior by losing the top label and seeing nothing as label. here is an example for what i'm talking about:
![Capture](https://user-images.githubusercontent.com/13780503/81800220-c711bd80-9512-11ea-96a1-44642eabf874.PNG)

Here we keeped the corrected behavior of material design and we say that there is no item selected.
now let's back to your suggession, here if we apply it we will lose the top label like this:
![Capture](https://user-images.githubusercontent.com/13780503/81800503-39829d80-9513-11ea-8050-4233b1a74050.PNG)
So the user can't even know the field is for what (no hint or label).
To resume, if the user choose to customize the dropdownBuilder he have simply just to apply custom UI for both item cases, like that he get always the correct behavior of material design, in your case you can simply add a Text and apply hint theme on it to say "Select a port".

**Comment by slavap** [comment]
@salim-lachdhaf I understand what you are saying, and I can return "Select a port" in case of null value. BUT I will loose nice animation from top to placeholder in that case:
![2020-05-13_4-14-17](https://user-images.githubusercontent.com/4129763/81806202-fef81100-94d0-11ea-87ff-86799db36ef5.gif)

And I cannot use just decoration, because I need to show code + name:
![image](https://user-images.githubusercontent.com/4129763/81806364-3666bd80-94d1-11ea-9278-c8bbc2180ce2.png)
![image](https://user-images.githubusercontent.com/4129763/81806392-3ebef880-94d1-11ea-8942-2701ca1ec0b9.png)

That's why property: bool dropdownBuilderSupportsNull = true
is completely solving this problem for me, and doesn't affect other users who don't want default behavior and animation, and always returning custom representation for null value.
I'm ok to return "Select a port", but all I want is default behavior with animation for null case, and there is no way for me to make it working.

**Comment by salim-lachdhaf** [comment]
> And I cannot use just decoration, because I need to show code + name:

Yes you can :) , Use item custom `itemAsString`

```
///this method will prevent the override of toString
  String portAsString() {
    return '#${this.code} ${this.name}';
  }
```

```
DropdownSearch<Port>(
  label: "Port",
  onFind: (String filter) => getData(filter),
  itemAsString: (Port p) => p.portAsString(),// <- override this ;)
  onChanged: (Port p) => print(p),
),
```

What do you think ?

**Comment by slavap** [comment]
@salim-lachdhaf 
You really hard to convince person :-)
I’m showing you not final version, code + Name will be more complex, and partially not alphabetical, I.e. icons as well.

**Comment by salim-lachdhaf** [comment]
The requested feature will be in the next pub , as a gift for you :)

**Comment by slavap** [comment]
@salim-lachdhaf thank you! Believe me it will be useful not only for me.
