### ISSUE TITLE
Error: Type 'EditableTextContextMenuBuilder' not found.

### ISSUE THREAD

**Issue by Taldorr** [salim-lachdhaf/searchable_dropdown#589]
**Describe the bug**
Just added the package to my web project and copied the example code:

```
DropdownSearch<String>.multiSelection(
    items: ["Brazil", "Italia (Disabled)", "Tunisia", 'Canada'],
    popupProps: PopupPropsMultiSelection.menu(
        showSelectedItems: true,
        disabledItemFn: (String s) => s.startsWith('I'),
    ),
    onChanged: print,
    selectedItems: ["Brazil"],
)
```

This error message showed up, when I launched the project:

```
Launching lib/main_offline.dart on Chrome in debug mode...
main_offline.dart:1
: Error: Type 'EditableTextContextMenuBuilder' not found.
text_field_props.dart:14
  final EditableTextContextMenuBuilder? contextMenuBuilder;

: Error: No named parameter with the name 'useSafeArea'.
dropdown_search.dart:578
      useSafeArea: widget.popupProps.modalBottomSheetProps.useSafeArea,

: Context: Found this candidate, but the arguments don't match.
bottom_sheet.dart:680
Future<T?> showModalBottomSheet<T>({
           ^^^^^^^^^^^^^^^^^^^^
: Error: Property 'context' cannot be accessed on 'OverlayState?' because it is potentially null.
dropdown_search.dart:603
- 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('../../../flutter/packages/flutter/lib/src/widgets/overlay.dart').
overlay.dart:1
Try accessing using ?. instead.
    var overlay = Overlay.of(context).context.findRenderObject() as RenderBox;
                                      ^^^^^^^

: Error: No named parameter with the name 'contextMenuBuilder'.
selection_widget.dart:471
                  contextMenuBuilder: widget.popupProps.searchFieldProps.contextMenuBuilder,
                  ^^^^^^^^^^^^^^^^^^
: Context: Found this candidate, but the arguments don't match.
text_field.dart:277
  const TextField({
        ^^^^^^^^^
: Error: 'EditableTextContextMenuBuilder' isn't a type.
text_field_props.dart:14
  final EditableTextContextMenuBuilder? contextMenuBuilder;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Failed to compile application.
Exited
```

**To Reproduce**
1. Add current version of package (5.0.6) to pubspec.yaml
2. Copy example code
3. Launch application

**Expected behavior**
No error

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Flutter version 3.3.10
 - Dart Version 2.18.6

**Comment by salim-lachdhaf** [comment]
please check your dependencies or try to clean cache

**Comment by maaelphd** [comment]
was getting the same error, and upon inspecting the error message, I noticed that it was originating from the dropdown_search-5.0.6\lib\src\properties\text_field_props.dart file.

I realized that in my project, I had been using version 5.0.5, but it appeared to be using version 5.0.6 from the cache at flutter\.pub-cache\hosted\pub.dartlang.org\dropdown_search-5.0.6.

What I did was remove the dependency from my project and then added it back. This seemed to force the correct version's dependency to be created in the cache.

Upon inspecting the files in version 5.0.6, it appeared that the property 'EditableTextContextMenuBuilder' was added to the text_field_props.dart file. Although it was declared in the class as "final EditableTextContextMenuBuilder? contextMenuBuilder;", it was not initialized in the constructor like the other properties, e.g., "this.contextMenuBuilder."

Since version 5.0.5 did not have this property, "downgrading" to 5.0.5 version resolved the issue, for me.

I'm not sure if this issue is related to the Flutter version, as I am using the same versions as @Taldorr .

System: Windows 10
Platform: Windows
Flutter version 3.3.10
Dart Version 2.18.6
