### ISSUE TITLE
Some parameters are not defined!

### ISSUE THREAD

**Issue by sabari7320** [salim-lachdhaf/searchable_dropdown#610]
![Screenshot 2023-11-16 161604](https://github.com/salim-lachdhaf/searchable_dropdown/assets/94843546/0d769cbc-ea04-4219-904d-80d35f602ea0)

1.)The named parameter 'showClearButton' isn't defined. (Documentation)  Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'showClearButton'.

2.)The named parameter 'searchBoxDecoration' isn't defined. (Documentation)  Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'searchBoxDecoration'

![Screenshot 2023-11-17 104943](https://github.com/salim-lachdhaf/searchable_dropdown/assets/94843546/6ffd60cd-07c2-456c-be59-888c99aa53fb)

3.)The named parameter 'showSelectedItem' isn't defined. (Documentation)  Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'showSelectedItem'

4.)The named parameter 'mode' isn't defined. (Documentation)  Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'mode'

5.)The named parameter 'showSearchBox' isn't defined. (Documentation)  Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'showSearchBox'

6.)The named parameter 'label' isn't defined. (Documentation)  Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'label'

**Comment by amirkarimistr** [comment]
**HI**

I hope this message finds you well. I recently upgraded my Flutter project to version 3.16.6 and encountered an issue with your library. The error message indicates that some parameters are not defined.

I believe this could be due to compatibility issues with the latest Flutter version. Could you please consider updating the library to ensure it remains compatible with the latest Flutter releases?


![drop_down_issue](https://github.com/salim-lachdhaf/searchable_dropdown/assets/72507762/9fabb72c-e72a-4855-a8cd-51ae18cb3946)

**Comment by salim-lachdhaf** [comment]
please don't hesitate to take a look to example page  here https://github.com/salim-lachdhaf/searchable_dropdown/blob/0db798a07a222435950c024abdbf8f8926798211/example/lib/main.dart

you have just to migrate to new version.
