### ISSUE TITLE
Filter is not working when entering single character

### ISSUE THREAD

**Issue by Nandhini-GA** [salim-lachdhaf/searchable_dropdown#619]
Filter is not showing proper result when typing single character (need to enter 2 or more characters to start filtering)
(Rarely working)
https://github.com/salim-lachdhaf/searchable_dropdown/assets/152958312/4aca85d7-40cc-4594-937c-da5a4899dc8d

**Comment by Nandhini-GA** [comment]
Uploading Screen Recording 2024-01-10 at 5.35.57 PM.mov…

**Comment by kvn-7** [comment]
This behavior is not a bug but rather intentional and follows a specific process when conducting a search. 

When you search for something, it does the following:

It makes all the letters lowercase.
Then, it checks if any of the options in the dropdown list contain the letters you typed. If they do, it shows those options.

For example, if you type "a," it will show you all the options that have the letter "a" in them.
