### ISSUE TITLE
Selected element properties dof the multiselect dropdown.

### ISSUE THREAD

**Issue by rradjab** [salim-lachdhaf/searchable_dropdown#684]
Thank you very much for such a simple and powerful package that simplifies the work and helps make the application beautiful and functional! I would be very glad and it would be very cool if you gave the opportunity to change the selected element of the multiselect dropdown. For example, the container size (32 by default), color, and so on, so that you don’t have to write the dropdownBuilder manually!
Good luck!

**Comment by salim-lachdhaf** [comment]
Well... in v6.0.1, the height constraint of 32 has been removed.

Now, back to giving chips props like other widgets. To be honest, I’ve thought about it a lot, and in the end, it’s not a good idea. First, because these chips are just a choice of mine, not a fixed widget like a dropdown or dialog, where the developer has no option other than changing its props.

In our case, the user has fully customizable chips (or other components). Sure, you might like my default chips and only want to change the color, which seems like a simple request with less code. But once you want to change the color, someone else will want to change the border, another will want to change the close icon, or hide it altogether, and so on. It would never end. That's why we've decided to give users the freedom to fully customize their chips. With the builder, you can give each chip a unique color, shape, etc., which would be impossible using only props.

Allowing the use of both props and the builder would confuse users and lead to conflicts. For example, someone might say, "I set the color to red, but it's not red" (because they overrode it with the builder). Should we merge the props with the builder? That would be impossible!

Back to reality: using the builder is neither complex nor requires long code. We've tried our best to make the library readable, easy to use, and customizable as possible.

In your case, you can use `dropdownBuilder` or, as shown below, the default chips use `primaryColorLight` from your theme. You just need to override it like this (same for text style ;) ):


```
Theme(
    data: ThemeData(primaryColorLight: Colors.red),
    child: DropdownSearch<UserModel>.multiSelection(  
        ....
    )
) 
```

**Comment by rradjab** [comment]
Thanks for the quick reply!

![image](https://github.com/user-attachments/assets/98f93f6d-4830-4333-b2e8-f5e725da6ed7)
I am quite satisfied with the colors you have chosen, but my problem is precisely in the height of the container,  ( now sizedbox, where height is 32) as can be seen from the image. (version 6.0.1)
![image](https://github.com/user-attachments/assets/8e6d58cc-b5be-4280-a2c9-e7a1484b9ad4)

To be honest, I have already tried through dropdownBuilder, but I could not figure out what to do with the _handleOnChangeSelectedItems() function when deleting or changing the selected set of elements. I still have to use the package in the stateful widget. Maybe there are other options? I would be very grateful.

**Comment by salim-lachdhaf** [comment]
No, the `SizedBox` is for the `IconButton,` not for the height of the chips. Now, you can have two lines in the chip, which wasn't possible before. We chose a height of 32 to ensure the final height of the form matches the other `TextField`.

You can control your dropdown using a `GlobalKey`.

Here is a full example of how to use the `dropdownBuilder` :

```
import 'package:dropdown_search/dropdown_search.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'dropdownSearch Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  final dropDownKey = GlobalKey<DropdownSearchState>();
  
  @override
  Widget build(BuildContext context) {
    Widget itemWidget(int item) {
      return Container(
        padding: EdgeInsets.only(left: 8, right: 1),
        margin: EdgeInsets.symmetric(horizontal: 2, vertical: 1),
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10),
          color: Colors.greenAccent,
        ),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Text('$item'),
            Padding(padding: EdgeInsets.only(left: 8)),
            SizedBox(
              width: 32,
              height: 32,
              child: IconButton(
                iconSize: 20,
                padding: EdgeInsets.zero,
                icon: Icon(Icons.close_outlined, size: 20),
                onPressed: () => dropDownKey.currentState?.removeItem(item),
              ),
            )
          ],
        ),
      );
    }

    return Scaffold(
      appBar: AppBar(title: Text('chips example')),
      body: Padding(
        padding: const EdgeInsets.all(8.0),
        child: DropdownSearch.multiSelection(
          key: dropDownKey,
          items: (filter, loadProps) => [1, 2, 3, 4, 5, 6, 7, 8, 9],
          dropdownBuilder: (context, selectedItems) {
            return Wrap(children: selectedItems.map((i) => itemWidget(i)).toList());
          },
        ),
      ),
    );
  }
}
```

**Comment by rradjab** [comment]
But height in screenshot doesnt match the height of the standart textfield. Sizedbox 32 makes him higher, when i changed it to 22 it shows normally. Using globalkey and builder makes everything more complicated, instead of using props. 

> Allowing the use of both props and the builder would confuse users and lead to conflicts. For example, someone might say, "I set the color to red, but it's not red" (because they overrode it with the builder). Should we merge the props with the builder? That would be impossible!
Yes i agree with you, but it makes the package more dynamic and advanced. (and there will be no need to create a builder if you can change several parameters with just a couple of lines)

This package is very convenient and simple and at the same time multifunctional. These features can make it much more convenient and understandable. 
PS: I only encountered the ingenious itemstring parameter in this package, for which I have great respect and gratitude to you!

**Comment by salim-lachdhaf** [comment]
Normally even with 32px of heigth you will get same heigth as normal TextField (tested on chrome, windows and android using default theme of material 3). If not check these things:
- your smalText style in theme 
- the padding used for the dropdownDecoration 

I'm working on other feature, i will see how can i make this part more customizable.

**Comment by rradjab** [comment]
thank you!
