### ISSUE TITLE
How to set height of dropdown_search widget?

### ISSUE THREAD

**Issue by robospot** [salim-lachdhaf/searchable_dropdown#7]
```
 return SizedBox(height: 40,
                                    child: DropdownSearch<Template>(
                                        dropDownSearchDecoration:
                                            InputDecoration(
                                                border: InputBorder.none,
                                                filled: true,
                                                fillColor: Color(0xffE8EBF7)),
                                        showClearButton: true,
                                     mode: Mode.MENU,
                                        items: templatestate.templates,
                                        itemAsString: (val) => val.templateName,
                                        selectedItem: _selection,
                                     onChanged: (val) => onSelectTemplate(
                                            mainState.inspection, val),
                                     showSearchBox: false,
                                        searchBoxDecoration: InputDecoration(
                                            border: InputBorder.none)),
                                  );
```
![image](https://user-images.githubusercontent.com/51660757/82095699-40263600-9708-11ea-8545-bc526c3df6db.png)

**Comment by salim-lachdhaf** [comment]
You can customize `dropdownBuilder` 
You can find here an examples :
https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/example/lib/main.dart

**Comment by lorensewusu** [comment]
Customising the `dropdownBuilder` does not change the height of the dropdown_search widget. It basically just changes the width of the displayed/selected item. There are lots of trailing padding around the widget which seems to make it look bigger in terms of height.
This is when i make the dropdownbuilder have a very small height, it basically did not affect the height of the widget itself.
![image](https://user-images.githubusercontent.com/6972732/89136608-7bc4e500-d52c-11ea-8148-067c3eff6717.png)

From the image below
![image](https://user-images.githubusercontent.com/6972732/89136663-bcbcf980-d52c-11ea-90f1-d1d195b6fa72.png)

You can see that with the same text style the dropdown search has a bigger height than the password textfield below.

If i try to reduce the height of the widget by putting it in a container and squashing the height, the dropdown button goes out of place, look at the screenshot below

![image](https://user-images.githubusercontent.com/6972732/89136748-19201900-d52d-11ea-83f6-393f0b3eff30.png)

**Comment by salim-lachdhaf** [comment]
In that case you can simply customize `dropDownButton` and `clearButton`

**Comment by ayberkcal** [comment]
I have faced same issue (not bug). I would like to decrease heght of dropdown widget. First of all I try to wrap with SizedBox widget and it worked good until validation message. When validation message showed, dropdown shortened in size. Thats normal because SizedBox constraint height. After that I saw this thread and try to figure out how affect dropdownBuilder size of dropdown widget? And I cannot decrease height of widget. As you can see icon size change does not affect height.
![image](https://user-images.githubusercontent.com/1190006/107868230-90971380-6e93-11eb-8497-1db43e377554.png)
Can you explain how can we change height of dropdown properly? Thank you.

**Comment by Fantasycheese** [comment]
`  
  ///function that manage Trailing icons(close, dropDown)
  Widget _manageTrailingIcons(T data) {
    return Row(
      mainAxisSize: MainAxisSize.min,
      mainAxisAlignment: MainAxisAlignment.end,
      children: <Widget>[
        if (data != null && widget.showClearButton)
          IconButton(
            icon: widget.clearButton ?? const Icon(Icons.clear, size: 24),
            onPressed: () => _handleOnChangeSelectedItem(null),
          ),
        IconButton( /////////////////////// size default to 24
          icon: widget.dropDownButton ?? ////////////////////// customizing dropDownButton doesn't help anyway
              const Icon(Icons.arrow_drop_down, size: 24),
          onPressed: () => _selectSearchMode(data),
        ),
      ],
    );
  }
`
I believe it is because the size of IconButton that wrapped around dropDownButton is default to 24. 
I bump into this issue while trying to remove trailing icon completely. Since there's no api to do that, I try to customize dropDownButton with an empty Container, but there's still something occupying space and I believe that is IconButton with size 24.
@salim-lachdhaf could you please take a look and see what you can do? Many thanks!
