### ISSUE TITLE
Probably `DropdownSearchBuilder` could have non nullable `selectedItem`

### ISSUE THREAD

**Issue by vasilich6107** [salim-lachdhaf/searchable_dropdown#706]
**Is your feature request related to a problem? Please describe.**

Here is an fn typedef

```dart
typedef DropdownSearchBuilder<T> = Widget Function(BuildContext context, T? selectedItem);
```

Selected item being defined as `nullable` at the same time input decorator states

```dart
isEmpty: getSelectedItem == null,
```

**Describe the solution you'd like**
This means that the content will not be shown, considering this - `selectedItem` for `DropdownSearchBuilder` could be non nullable cause there is no chance it will be shown.

**Describe alternatives you've considered**
```dart
dropdownBuilder: (_, item) {
        if (item == null) {
          return const SizedBox.shrink();
        }
        return Row(
          children: [
            ...item
          ],
        );
      },
```

**Comment by salim-lachdhaf** [comment]
`DropdownSearchBuilder` should be a `nullable` `selectedItem` otherwise, it will be impossible to represent "nothing" value .

`isEmpty` only affects the display of the `hint` or `label` in the dropdown.

**Behavior:**
- By default: The hint appears inside the text field if the selected item is `null`. If an item is selected, the hint is displayed as a label.
- When using `dropdownBuilder`: The behavior depends on how the developer handles `null` values.

**Examples:**

1. If the developer handles `null` as follows, the `hint` remains inside the text field without issue:
   ```dart
   dropdownBuilder: (_, item) {
     if (item == null) {
       return const SizedBox.shrink();
     }
     return Row(
       children: [
         ...item
       ],
     );
   },
   ```

2. If the developer uses a non-empty or visible widget for a `null` item, like this:
   ```dart
   dropdownBuilder: (_, item) {
     if (item == null) {
       return Text('No item selected');
     }
     return Row(
       children: [
         ...item
       ],
     );
   },
   ```
   In this case, the `hint` is hidden by default, and the developer should use `floatingLabelBehavior` to explicitly show the `hint` as a `label`.

For more context, you can refer to this related topic: [GitHub issue #515](https://github.com/salim-lachdhaf/dropdown_search/issues/515).
