### ISSUE TITLE
Not able to search item list

### ISSUE THREAD

**Issue by shivanijha002** [salim-lachdhaf/searchable_dropdown#76]
I am facing difficulty as search is not working. Also dropdown selection shows value as DropDownMenuItem<dynamic> instead of selected Data.

Please refer to below code snippet:
String selectedData;
List<DropdownMenuItem> dropdownMenuItemList = [DropdownMenuItem(
        child: Text('Data 1'),
        value: 'Data1',
      ),
      DropdownMenuItem(
        child: Text('Data 2'),
        value: 'Data2',
      ),
      DropdownMenuItem(
        child: Text('Data 3'),
        value: 'Data3',
      ),
      DropdownMenuItem(
        child: Text('Data 4'),
        value: 'Data4',
      )];

DropdownSearch(
			mode: Mode.DIALOG,
			selectedItem: selectedData,
			items: dropdownMenuItemList,
			label: 'My Data',
			showSearchBox: true,
			onChanged: (value) {
			  print(value); //prints 'DropDownMenuItem<<dynamic>>', I am expecting it to be 'Data 1'.
			  setState(() {
				selectedData = value.value.toString();
			  });
			},
			validator: Validator.valueExists,
			showClearButton: false,
			popupTitle: Container(
			  padding: EdgeInsets.all(8.0),
			  child: Text(
				text: 'My Data',
			  ),
			),
			popupItemBuilder:
				(context, item, isSelected) {
			  return Container(
				decoration: BoxDecoration(
				  border: Border.all(
					  color: Colors.grey[50]),
				),
				child: ListTile(
				  selected: (item.child.data ==
					  selectedData),
				  title: item.child,
				),
			  );
			},
		  ),

**Comment by salim-lachdhaf** [comment]
There is some fixes in your code:
1- you don't have to use a global variable and setState to manage it, you can use globalKey and access to the selected item anywhere and the plugin will show by itselef the selected value (check plugin example)

2- set searchableDropdown type as `DropdownSearch<DropdownMenuItem>(...)`

3- remove `selectedItem` because there no initial item in your case , so optomize it.

4- add `itemAsString:(DropdownMenuItem v) => v.value;`
This line will define how and what you what to show your object

5- replace ```
selected: (item.child.data ==
selectedData),
```
With 
`selected: isSelected`,

Don't forget to add :
`compareFn:(item, selected) => item.value == selected.value;`

6- of course `print(value) `will print `DropDownMenuItem` because your using a dropdownSearch of `DropDownMenuItem`.
To get the wished data just write `print (value.value)`

7- hope this helps you.

**Comment by shivanijha002** [comment]
Thanks. It worked 👍
